# Generated by Django 5.0.6 on 2024-06-06 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='option',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='price_per_day',
            new_name='price',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
    ]
