# Generated by Django 5.0.6 on 2024-06-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_remove_car_option_rename_price_per_day_car_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='uploads/vehicles/'),
        ),
    ]
