# Generated by Django 5.0.6 on 2024-06-07 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_car_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='price',
        ),
    ]
